### ISSUE TITLE
Пищевой синтез и фляга с возможностью самовосполнения

### ISSUE THREAD

**Issue by TheGalaxx** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#1]
Создание пищевых компаундов 3х уровней.(все перечистенное должно быть весьма дорого в плане энергии и не особо сильно в плане редких ресурсов)
* 1 уровень(могут быть белковыми и овощными, по статам чуть хуже обычной еды в плане питательности, но срок хранения больше)
Простые компаунды получаемые путем смешивания жидкостей/их обработки в химреакторе и последующем переработки в саму еду в жидкостном отвердителе/автоклаве (энергия IV+ тира для всех рецептов, чистая комната не требуются)
* 2 уровень(могут быть всех типов и содержать до 2-3 типов питания одновременно, питательность на уровне обычной пищи, срок хранения +-как у консервов из галактика)
Получение путем реакций в б. химреакторе с участием кальция, трикальцийфосфата и околоподобных вещей с последующим смешиванием(для получения пищи с несколькими типами питания использовать смешивание с добавлением доп. компонентов) переработка в еду в отвердителе/автоклаве (использование min. luv-zpm энергии, наличие чистой комнаты)
* 3 уровень(могут содержать все типы питания, на 10-40% питательнее обычной еды, хранится в 5 раз дольше консервов из галактика
Использование жидкостей из рецептов пищи 2-го уровня, смешивание путем использование термояда/UV+ смесителя(в случае смесителя необходима стерильная комната) с последующем добавлением различных орг. веществ в химреакторе, превращение в твердую пищу в автоклаве/отвердителе(для всех процессов, кроме смешивания в термояде требуется стерильная комната)

Синтез пищи/воды в полевых условиях
* Полевой кристалл синтеза - предмет наподобие терминала, который можно улучшать добавляя туда различные механизмы, имеет 3 режима работы.
 1) Преобразование жидкого компаунда в готовую пищу(базовая функция, доступная без улучшений)
 2) Синтез пищи из загруженных заранее компонентов, только пища 1 уровня
 3) Синтез пищи из неорганических компонентов, только пища 1 уровня(требует значительно большее кол-во энергии чем остальные функции)
 * Электрофляга (имеет 2 режима работы и собственную емкость)
 1) Синтез воды из кислорода и водорода при их наличии в емкостях фляги
 2) Синтез воды путем ее сбора из окружающего пространства(требует больше энергии, работает на земле/в помещениях с кислородом)

**Comment by Xikaro** [comment]
https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=25746141
переместил, это закрою
