### ISSUE TITLE
Дюп с сосудом

### ISSUE THREAD

**Issue by KarandashKosmos** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#100]
### Тип используемого модпака

Default

### Среда запуска

Все

### Новые миры

Да

### Ожидаемое поведение

Интерфейс не откроется

### Фактическое поведение

Открывается интерфейс, из которого можно дюпать вещи.

### Действия по воспроизведению

1) Зайти в игру
2) Взять сосуд из TFC
3) Нажать ПКМ и поставить его на землю (вроде-бы клавиша C) одновременно
4) Если интерфейс открылся, а сосуд поставлен на землю, забрать вещи

### Дополнительная информация

Знаю, что дюп известный, но он мощный.
Также это можно провернуть с сумочкой из LittleTiles.
С рюкзаком почему-то не работает.

**Comment by Xikaro** [comment]
https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=25746421
перенос
