### ISSUE TITLE
Can't craft luminous crafting table.

### ISSUE THREAD

**Issue by Sehrank8** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#105]
### Version modpack Used

Extended

### Environment

Forge Server

### New Worlds

Yes

### Expected Behavior

I excpect to be able to craft a luminous crafting table when crafting next to a crystal from astral sorcery.

### Actual Behavior

Can't craft a lumious crafting table with modded crafting tables.

### Steps to Reproduce

1)Find astral sorcery structure
2)Put a crafing table under the crystal
3)Try to craft a luminous crafting table

**Comment by msgerbs** [comment]
This seems to be impossible from everything I can find, Astral seems to _require_ a vanilla crafting table. There is a workaround which slightly reduces the complexity of the first few steps of Astral by removing the requirement to be crafted near a crystal:

`B:LightProximity-Altar=false`

`B:LightProximity-ResonatingWand=false`

**Comment by Xikaro** [comment]
#148
