### ISSUE TITLE
баг крафта с короной 

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#130]
### Тип используемого модпака

Default

### Среда запуска

проверил в одиночке, а2кат чекал на сервере

### Новые миры

Да

### Ожидаемое поведение

крафт должен быть скрафчен любой ценой!
![image](https://user-images.githubusercontent.com/112543401/225306057-8b839a3c-ce94-43dd-8c17-2d0ac684c04d.png)

### Фактическое поведение

![image](https://user-images.githubusercontent.com/112543401/225305880-581f1a34-0123-428f-b36c-aa3a88670634.png)

### Действия по воспроизведению

закидываешь ресы в крафт

### Дополнительная информация

не рабтают крафты обоих видов корон платины и золота

**Comment by Xikaro** [comment]
исправлено в дев
