### ISSUE TITLE
При распиле досок на палки пилой, пила полностью исчезает после первого же крафта

### ISSUE THREAD

**Issue by g-gost** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#133]
### Тип используемого модпака

Default

### Среда запуска

одиночная игра

### Новые миры

Да

### Ожидаемое поведение

При распиле просто теряется прочность пилы

### Фактическое поведение

При распиле 1 доски неважно в каком состоянии пила исчезает

### Действия по воспроизведению

Распилить доски через меню крафта

**Comment by Xikaro** [comment]
исправлено в дев
