### ISSUE TITLE
Не работает крафт листов металла 

### ISSUE THREAD

**Issue by Bear-Creator** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#135]
### Тип используемого модпака

Default

### Среда запуска

Сервер

### Новые миры

Нет

### Ожидаемое поведение

Металлические листы должны крафтится

### Фактическое поведение

Не крафтится

### Действия по воспроизведению

выложить рецепт

### Дополнительная информация

Скорее всего не работает из-за GT напильника

**Comment by Xikaro** [comment]
можно хотяб скрин, что именно должно крафтится
