### ISSUE TITLE
Unable to make wood tones

### ISSUE THREAD

**Issue by EternisField** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#138]
### Version modpack Used

Default

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Find recipes for wood tones in JEI and be able to make them

### Actual Behavior

Unable to find the recipe for Wood Tongs in JEI

### Steps to Reproduce

Search for recipes in JEI

**Comment by Xikaro** [comment]
![Screenshot_67](https://user-images.githubusercontent.com/55663835/226387162-df18e270-e95e-42c7-b80a-5c9f729449b1.png)
![Screenshot_68](https://user-images.githubusercontent.com/55663835/226387171-3e51a94a-3dbb-4064-8fe3-a7118b46f6d6.png)
