### ISSUE TITLE
An empty wood bucket crafts into unlimited yeast, desyncing the client when they do other actions afterwards

### ISSUE THREAD

**Issue by MostFunGuy** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#140]
### Version modpack Used

Extended

### Environment

Forge Server

### New Worlds

Yes

### Expected Behavior

Expect empty wood bucket to not craft into anything.

### Actual Behavior

Empty wood bucket crafts into unlimited yeast, desyncing the client, filling their inventory:

https://i.gyazo.com/ada4ed3f6b9db11f96fff9c6a4def3ac.mp4

And causing all kinds of desync issues:

https://i.gyazo.com/ac698e0b7db01bf497872d1c4088b367.mp4

https://i.gyazo.com/6f059a310dc3830ae4dedfba16def159.mp4

### Steps to Reproduce

1: Get wooden bucket

2: Insert into crafting table (inventory, block crafting table, any)

3: See the result is yeast

4: Craft yeast

5: You can no longer drop items from your inventory, thaumometer shows no vis anywhere, invisible items in your inventory, etc. 

### Additional Information

This was not present as of the most previous release (4.2.5). This started in 4.2.6

**Comment by FirinMaLazors** [comment]
I can confirm I get yeast starter when I craft an empty bucket.  I haven't checked for the other effects.

**Comment by Xikaro** [comment]
wtf

**Comment by Xikaro** [comment]
temporarily returned the recipe to ct
