### ISSUE TITLE
Дюп стали

### ISSUE THREAD

**Issue by KarandashKosmos** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#142]
### Тип используемого модпака

Default

### Среда запуска

Все

### Новые миры

Да

### Ожидаемое поведение

-

### Фактическое поведение

Есть возможность дюпать сталь через крафт.

### Действия по воспроизведению

Дюп стали через рецепты:
![image](https://cdn.discordapp.com/attachments/742984273446830124/1089502289779228722/image.png)
![image](https://cdn.discordapp.com/attachments/742984273446830124/1089502290098012260/image.png)

**Comment by Xikaro** [comment]
в R7 будет изменено, пока закрываю
