### ISSUE TITLE
Не делается водород из соли

### ISSUE THREAD

**Issue by nikiforr** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#144]
### Тип используемого модпака

Default

### Среда запуска

сервер Forge

### Новые миры

Да

### Ожидаемое поведение

![image2](https://user-images.githubusercontent.com/88327057/227949258-9cb05dbc-ea44-4fa9-b8a1-37044e24c5b5.png)

### Фактическое поведение

![image1](https://user-images.githubusercontent.com/88327057/227949391-12ce6d57-d394-4ece-90b0-d003a5d2cfea.png)

### Действия по воспроизведению

При попытке смешать соль и воду в электролизёре оно делает хлор даже если всё что нужно для водорода поставлено

**Comment by Xikaro** [comment]
Исправлено в дев
![Снимок экрана 2023-04-16 045305](https://user-images.githubusercontent.com/55663835/232258885-3293f713-09a1-489b-87ab-1a34d0286e8d.png)
