### ISSUE TITLE
Mod mismatch for SuperMartijn642's Core Lib on server

### ISSUE THREAD

**Issue by msgerbs** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#145]
### Version modpack Used

Extended

### Environment

Forge Server

### New Worlds

Yes

### Expected Behavior

Being able to join the server

### Actual Behavior

![image](https://user-images.githubusercontent.com/1313921/228137482-774df766-20b7-4a20-9ff8-2c8363810a74.png)
 Mod version mismatch between client and server pack.

### Steps to Reproduce

Install server and client. Join server.

**Comment by Xikaro** [comment]
fixed in dev
