### ISSUE TITLE
Проблема крафта снарядов пращи

### ISSUE THREAD

**Issue by KarandashKosmos** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#146]
### Тип используемого модпака

Default

### Среда запуска

Все

### Новые миры

Да

### Ожидаемое поведение

-

### Фактическое поведение

Не крафтятся предметы. В JEI рецепт есть. при "+" тоже не работает.
![image](https://user-images.githubusercontent.com/95368060/228175101-7725b652-f055-4378-b7af-6c1d04aa2f68.png)
![image](https://user-images.githubusercontent.com/95368060/228175173-8955e6a8-8b7b-4afb-a254-bd6ee526b57f.png)
![image](https://user-images.githubusercontent.com/95368060/228175213-9ee8efdd-1cee-4e2a-be7b-4be58c58b138.png)
![image](https://user-images.githubusercontent.com/95368060/228175235-0ab1eb8e-dbdc-4dbd-96dd-f4211df82536.png)

### Действия по воспроизведению

-

### Дополнительная информация

-

**Comment by Xikaro** [comment]
исправлено в дев
