### ISSUE TITLE
Доработка автосборки extended версии

### ISSUE THREAD

**Issue by Xikaro** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#147]
### Тип используемого модпака

Extended

### Связанная проблема

Постоянно копирование манифеста и мод листа

### Ваше решение

С помощью скрипта, сделать встраивание заголовка и части модов, входящих только в extended версию, в манифест и модлист, обычной версии

### Дополнительная информация

Избавляемся от рутины

**Comment by FriendlyCube** [comment]
прикольно

**Comment by Xikaro** [comment]
сделал
