### ISSUE TITLE
Forge Mod Loader found a problem with Minecraft Installation: Version 4.2.8-Extended

### ISSUE THREAD

**Issue by Darian461** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#149]
### Version modpack Used

Extended

### Environment

Booting Minecraft

### New Worlds

No

### Expected Behavior

TFG:NH boots as normal

### Actual Behavior

Forge Mod loader finds a problem with the minecraft installation, mod sources that are duplicate.

### Steps to Reproduce

In polyMC, add instance of the modpack version 4.2.8

Launch modpack.

### Additional Information

Screenshot of the screen that follows plus latest.log in case its needed.
![image](https://user-images.githubusercontent.com/109935189/229223353-86a32a91-5213-449e-9008-3653b4765213.png)
[latest.log](https://github.com/TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x/files/11125747/latest.log)

**Comment by tocandyman** [comment]
Также в данной версии отсутствует метадата у модов.

**Comment by Xikaro** [comment]
исправлено в дев
