### ISSUE TITLE
Крафт печатных плат из Project Red

### ISSUE THREAD

**Issue by CTPaHHInK** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#150]
### Тип используемого модпака

Default

### Среда запуска

Мультиплеер, свой сервер

### Новые миры

Не уверен

### Ожидаемое поведение

Крафт печатных плат из Project Red из любого камня

### Фактическое поведение

Крафт печатных плат из Project Red только из ванильных и их гладких версий

### Действия по воспроизведению

Крафт печатных плат из Project Red
[https://i.imgur.com/5jviQl7.png](url)

**Comment by CTPaHHInK** [comment]
Закину сюда же крафт клавиатуры из OC, там только ванильные кнопки

**Comment by Xikaro** [comment]
Плату исправил, по клавиатуре, в кнопках юзается все по ордикту, и тфк кнопки подходят
![Снимок экрана 2023-04-16 042721](https://user-images.githubusercontent.com/55663835/232258159-34a2733e-f304-4a3d-a4c1-c62e2449c4ee.png)

PS
Может я ранее исправил и забыл
