### ISSUE TITLE
ID воды из TFC

### ISSUE THREAD

**Issue by Raptor7011** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#151]
### Ваш вопрос

Хочу поставить шейдры, настраивая block.properties столкнулся с тем, что не могу найти ID воды из TFC. Пробовал различные варианты типа tfc:fresh_water. F3 + H из optifine не отображает ID воды именно из TFC, хоть с ExtraPlanets такой проблемы не возникло. Если кто-то уже настраивал шейдеры, буду рад, если вы поделитесь своими настройками.

**Comment by Xikaro** [comment]
https://github.com/TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x/tree/main/.minecraft/shaderpacks

Тут уже есть готовые
