### ISSUE TITLE
Дюп редстоуна глоустоуна

### ISSUE THREAD

**Issue by KraftKraftKraft** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#154]
### Тип используемого модпака

Default

### Среда запуска

1

### Новые миры

Да

### Ожидаемое поведение

1

### Фактическое поведение

![image](https://user-images.githubusercontent.com/129421418/230091610-9010b2b5-f4a0-4849-80cc-c4c3f4fb0073.png)
![image](https://user-images.githubusercontent.com/129421418/230091653-843a140f-cdb7-4f03-881a-99b9e0231bea.png)
И в дуговой тоже 

### Действия по воспроизведению

1

### Дополнительная информация

Не совсем дюп, но когда лень искать жилу тоже пойдет)

**Comment by Xikaro** [comment]
исправлено в 4.3.0
