### ISSUE TITLE
У работающей паровой мультиплавильни отсутствует текстура у "блока корпуса топки".

### ISSUE THREAD

**Issue by BerdyshevKirill** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#155]
### Тип используемого модпака

Default

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Текстура должна нормально отображаться.

### Фактическое поведение

![2023-04-08_05 09 29](https://user-images.githubusercontent.com/95979027/230699412-187af43f-c9df-4f94-9cb6-489b18539e6a.png)

### Действия по воспроизведению

1. Запустить работу плавильни любым ресурсом.
2. Наблюдать результат.

### Дополнительная информация

Косяк виден только при включённом ресурспаке: "TFG-Resourcepacks-1.0.5".

![Screenshot_2](https://user-images.githubusercontent.com/95979027/230699587-b66e625a-63ef-4eae-a726-34f35f48b985.png)

**Comment by Xikaro** [comment]
ок

**Comment by Xikaro** [comment]
исправил
