### ISSUE TITLE
Animals randomly disappear

### ISSUE THREAD

**Issue by FirinMaLazors** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#158]
### Version modpack Used

Default

### Environment

Official multiplayer server

### New Worlds

Unsure

### Expected Behavior

When keeping animals that have been familiarized and/or attached with a lead to a fence post or grindstone, the general expectation is that they don't despawn.

### Actual Behavior

At least three times now, animals have randomly disappeared, even when satisfying the above conditions.  The first time, I was keeping a bunch of goats in a pen outside, and some days later, they disappeared, but not the llama I was keeping on a grindstone inside; the second time, I had a bunch of llamas inside a building all leashed to a post or a grindstone, and they all disappeared at the same time some days later; the third and last time, I was keeping some horses outside on grindstones, and some days after keeping them there, they all disappeared - to be replaced apparently by a couple of rabbits and a goat? - except for one, which was in a different chunk from the ones that did disappear.

### Steps to Reproduce

Keep some domesticated animals in a chunk for some days (30?  could be more, could be less).  Check in on them occasionally to see if they've disappeared or not.

### Additional Information

I notice that maybe it's chunk-based, so maybe when the game is updating to replace old, aged animals with new ones, it's not actually checking to see whether they've been familiarized or leashed/roped?

**Comment by Xikaro** [comment]
It was due to automatic cleaning of mobs, right now this feature is disabled, so I think unless absolutely necessary, I will not use it, sorry
