### ISSUE TITLE
Перемешанные рецепты синей и красной сталей

### ISSUE THREAD

**Issue by 8oyNextDoor** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#159]
### Тип используемого модпака

Extended

### Среда запуска

Одиночка

### Новые миры

Да

### Ожидаемое поведение

Одинаковые рецепты сталей в тфк и гт

### Фактическое поведение

Добавки к сталям перемешаны между модами

### Действия по воспроизведению

Сравнить рецепты сталей жидких версий из тфк и пыли из гт

**Comment by 8oyNextDoor** [comment]
![image](https://user-images.githubusercontent.com/130379681/230925267-350df45e-51fe-44e6-8f01-7447a82648d6.png)
![image](https://user-images.githubusercontent.com/130379681/230925275-1834efde-ecd2-473a-862c-bd1556fba69b.png)
![image](https://user-images.githubusercontent.com/130379681/230925286-d2ccd3b1-5fcd-4342-8a0b-eae73eb1699f.png)
![image](https://user-images.githubusercontent.com/130379681/230925298-bae1b2ac-c120-4afb-9e46-ffbfce3abb89.png)

**Comment by Xikaro** [comment]
исправится в R7 версии сборки
