### ISSUE TITLE
Графическая ошибка ресурспака

### ISSUE THREAD

**Issue by CmBSinka** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#160]
### Тип используемого модпака

Default

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Блок не должен пропадать при дыхании на него.

### Фактическое поведение

Блок пропадает при дыхании на него.
![image](https://user-images.githubusercontent.com/43815006/231294410-c7d4aa77-b0d3-43b3-967d-4489295118be.png)

### Действия по воспроизведению

1) Включить ресурс пак
2) Найти блок светокамня
3) Если на улице зима, ваш персонаж будешь создавать пар
4) Пар попавший на светокамень заставляет, последний стать прозрачным. (Хорошо видно если камень вдалеке)

**Comment by Xikaro** [comment]
Без ресурспака все нормально? Можешь сделать такой же скрин, только без ресурспака

**Comment by CmBSinka** [comment]
![image](https://user-images.githubusercontent.com/43815006/231296748-4b78c4a3-f120-4847-8a25-65af9b42e7b2.png)

**Comment by Xikaro** [comment]
после проверок, это ошибка рендера эммисии в оптифайне, так что с нашей стороны это не исправить
