### ISSUE TITLE
Дюп Кованного железа

### ISSUE THREAD

**Issue by Omirian** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#161]
### Тип используемого модпака

Default

### Среда запуска

Одиночная игра, сервер.

### Новые миры

Да

### Ожидаемое поведение

При переработке Ведра из кованного железа в Дуговой печи получается 1 Кованное железо (Слиток)
При переработке Ведра из кованного железа в Измельчителе получается 1 Кованное железо (Пыль)

### Фактическое поведение

При крафте Ведра из кованного железа (#5775/0) используется одна пластина Кованного железа (соответственно один слиток). Далее это ведро в Дуговой печи и Измельчителе можно преобразовать в эквивалент 3 слитков Кованного железа и т.д., продолжая увеличивать количество слитков втрое.
![Снимок](https://user-images.githubusercontent.com/121557882/231295567-af779c61-e153-404a-b153-fd34577e50de.PNG)
![Снимок0](https://user-images.githubusercontent.com/121557882/231295570-677b3f4b-4654-4132-acf8-e481dff98749.PNG)
![Снимок1](https://user-images.githubusercontent.com/121557882/231295573-fe46febd-ac3c-46e6-90ec-4aef12025269.PNG)

### Действия по воспроизведению

Переработать Ведро в измельчителе или дуговой печи. Дюп виден даже по крафтам в JEI.

**Comment by Xikaro** [comment]
Будет исправлено в R7
