### ISSUE TITLE
Невозможный рецепт ковки оголовья геологического молота (любого)

### ISSUE THREAD

**Issue by TDumpling** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#162]
### Тип используемого модпака

Default

### Среда запуска

одиночная игра, игра по локальной сети

### Новые миры

Да

### Ожидаемое поведение

Рецепт ковки оголовья геологического молота (из которого делается геологическая кирка) который можно выполнить.
![изображение_2023-04-13_182734847](https://user-images.githubusercontent.com/42238325/231808937-4a81eb0e-df61-4ea8-abcd-5fed62425291.png)

### Фактическое поведение

Два действия необходимо совершить именно последними, что невозможно. Проблема наблюдается у рецептов из всех материалов, рецепты литья и формовки работают корректно.
![изображение_2023-04-13_182207889](https://user-images.githubusercontent.com/42238325/231807444-f4ee0298-b2bb-47f7-8f36-11b52e0d6392.png)
![изображение_2023-04-13_182221212](https://user-images.githubusercontent.com/42238325/231807502-14f7cb7b-5c6c-48b2-8ffe-2f0864b6d0e9.png)
![изображение_2023-04-13_182232218](https://user-images.githubusercontent.com/42238325/231807546-6d4b5055-63e8-4cda-ae8a-043165268be6.png)
![image](https://user-images.githubusercontent.com/42238325/231807589-f990eb45-21e7-479c-8de0-7c5676f1603a.png)

### Действия по воспроизведению

Положить слиток кованного железа/бронзы/меди и т.д. в наковальню и выбрать рецепт оголовья геологического молота

**Comment by Xikaro** [comment]
исправлено
