### ISSUE TITLE
Неправильное описание квеста на медную стамеску

### ISSUE THREAD

**Issue by tocandyman** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#163]
### Тип используемого модпака

Extended 4.2.8

### Среда запуска

Сервер Forge (свой)

### Новые миры

Да

### Ожидаемое поведение

Ожидается описание стамески

### Фактическое поведение

![изображение](https://user-images.githubusercontent.com/34441740/231870435-12ebf5c3-87a0-4c52-90fd-b969599c0d8e.png)
а по факту описание геологической кирки

### Действия по воспроизведению

Открыть описание квеста на русском языке

### Дополнительная информация

Вероятно под пивом...

**Comment by Xikaro** [comment]
Исправил
![Снимок экрана 2023-04-16 043146](https://user-images.githubusercontent.com/55663835/232258296-6ad1b9d7-77a7-4a07-8d96-8748bedbf2c8.png)
