### ISSUE TITLE
Электролиз соли с водой

### ISSUE THREAD

**Issue by KraftKraftKraft** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#164]
### Тип используемого модпака

Default

### Среда запуска

1

### Новые миры

Да

### Ожидаемое поведение

1

### Фактическое поведение

![image](https://user-images.githubusercontent.com/129421418/231996843-32dd4710-b5d9-48ca-b4da-93eecf07cec3.png)
Этот рец не работает
![image](https://user-images.githubusercontent.com/129421418/231997666-e39974fc-c929-4720-8092-b73821585fc8.png)

Потому что есть два реца соли без воды, и один из них без программы, что тут же запускает электролиз без воды.

### Действия по воспроизведению

1

**Comment by Xikaro** [comment]
дубль #144
