### ISSUE TITLE
Нет текстурки у упаковочной машины

### ISSUE THREAD

**Issue by 8oyNextDoor** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#165]
### Тип используемого модпака

Extended

### Среда запуска

Одиночка

### Новые миры

Да

### Ожидаемое поведение

Нормальная текстурка

### Фактическое поведение

Плохая текстурка

### Действия по воспроизведению

Включить упаковочную машину (canning machine )

### Дополнительная информация

![image](https://user-images.githubusercontent.com/130379681/232255519-50c7a56b-8b26-4a88-a615-9e6bde1a00b0.png)

**Comment by Xikaro** [comment]
исправил
