### ISSUE TITLE
Крафт кнопок, клавиатуры и её компанентов

### ISSUE THREAD

**Issue by CTPaHHInK** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#166]
### Тип используемого модпака

Default

### Среда запуска

Мультиплеер, свой сервер, одиночка

### Новые миры

Да

### Ожидаемое поведение

Крафт клавиатуры и её кнопок(в том числе самих кнопок( ТОЛЬКО из ванильных блоков(!) ) )

### Фактическое поведение

Невозможен

### Действия по воспроизведению

Крафт в сборищке

### Дополнительная информация

Исправь кнопки в крафте, чтобы из TFC можно было использовать и сами крафты, крафтится только один тип

**Comment by Xikaro** [comment]
Я же писал что крафтится всё, 
Или скрины кидай
