### ISSUE TITLE
Неправильное описание задачи квеста

### ISSUE THREAD

**Issue by 8oyNextDoor** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#167]
### Тип используемого модпака

Extended

### Среда запуска

Одиночка

### Новые миры

Да

### Ожидаемое поведение

Понятная задача квеста

### Фактическое поведение

![image](https://user-images.githubusercontent.com/130379681/232347136-50f25728-fb60-43d5-af1a-902bc6fe9033.png)

### Действия по воспроизведению

![image](https://user-images.githubusercontent.com/130379681/232347177-591d1e73-7ffc-4f29-8ddf-5546821ccfe9.png)
Мв квест с тнт на картинке

**Comment by Xikaro** [comment]
не воспроизвелось у меня, попробуй на следующей версии проверить, которая выйдет, возможно у тебя папка с ресурсами не прогрузилась
