### ISSUE TITLE
Не правильное описание рецепта

### ISSUE THREAD

**Issue by tocandyman** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#169]
### Тип используемого модпака

Default

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

Рецепт создания полотна пилы

### Фактическое поведение

Рецепт создания лезвия ножа

### Действия по воспроизведению

открыть рецепт на русском языке

### Дополнительная информация

![2023-04-19_01 38 24](https://user-images.githubusercontent.com/34441740/232872846-05b44c9a-6614-4392-a00b-625ac659706e.png)

**Comment by Xikaro** [comment]
исправлено
