### ISSUE TITLE
Неправильное описание квеста англ. версии

### ISSUE THREAD

**Issue by 8oyNextDoor** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#170]
### Тип используемого модпака

Extended

### Среда запуска

Одиночка

### Новые миры

Да

### Ожидаемое поведение

Правильное описание квеста

### Фактическое поведение

![image](https://user-images.githubusercontent.com/130379681/233222741-8760f81e-95a7-4baa-8edb-fb5557e7d6f6.png)

### Действия по воспроизведению

Вот этот МВ квест
![image](https://user-images.githubusercontent.com/130379681/233222801-59495ed6-88a7-4a22-83ed-d2bbebe6258e.png)

**Comment by Xikaro** [comment]
исправлено
