### ISSUE TITLE
Book is hidden in JEI

### ISSUE THREAD

**Issue by msgerbs** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#171]
### Version modpack Used

Default

### Environment

Forge Server

### New Worlds

Yes

### Expected Behavior

I should be able to see books in JEI.

### Actual Behavior

Although books are craftable, they are hidden in JEI.

### Steps to Reproduce

Search JEI for Book.

### Additional Information

Seems to have been changed when the groovyscript migration happened in d3ba6c7

**Comment by Xikaro** [comment]
what books are you talking about?

**Comment by msgerbs** [comment]
minecraft:book

**Comment by Xikaro** [comment]
fixed in dev
