### ISSUE TITLE
Не работает Рецепт Очищеной Руды Сфалетита в Рудопромывочной Машине.

### ISSUE THREAD

**Issue by Andrei-Mudrov-archmage** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#172]
### Тип используемого модпака

Default

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

В Рудопромывочной Машине сфалетит и вода дадут очищеную руду.

### Фактическое поведение

Рецепт не запускается.

### Действия по воспроизведению

Рудопромывочник ЛВ уровня.
Кладём туда воду пресную или солёную.
Можно ещё Схему в конфигурации 2.

### Дополнительная информация

![image](https://user-images.githubusercontent.com/44801908/233821516-2d0a40e0-1691-4b1a-a51b-08fd64b86450.png)
![image](https://user-images.githubusercontent.com/44801908/233821522-828beae7-0a4e-46fe-bd31-73eda5919f80.png)
![image](https://user-images.githubusercontent.com/44801908/233821528-5d2cf9ff-1f94-4a81-add2-5a112eeb22ee.png)
![image](https://user-images.githubusercontent.com/44801908/233821533-e1308dc5-72ed-4e38-ae47-4e71a614d050.png)

**Comment by Xikaro** [comment]
В рецепте используется только ванильная вода и дистиллированная

**Comment by Andrei-Mudrov-archmage** [comment]
> В рецепте используется только ванильная вода и дистиллированная

Что за ванильная вода? Как её получить?

**Comment by Xikaro** [comment]
Ванильная, это та которая по умолчанию в обычном Майне, получить ее можно в больших количествах через улучшение бесконечная вода
