### ISSUE TITLE
Ошибка в описании рецепта на кожу в бочке с известковой водой WAILA

### ISSUE THREAD

**Issue by tocandyman** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#173]
### Тип используемого модпака

Default

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

Должно отобразить рецепт и время.

### Фактическое поведение

Выводит строку с ошибкой

### Действия по воспроизведению

Поместить кожу в известковую воду в бочке и закрыть. ![изображение](https://user-images.githubusercontent.com/34441740/233823297-5832c4da-6ee3-4667-8d96-b98aabfd7425.png)

**Comment by tocandyman** [comment]
Также на следующем шаге промывки чистой водой. 
![изображение](https://user-images.githubusercontent.com/34441740/233823642-c396c666-ea79-4dc3-a477-f8c47e173857.png)

**Comment by Xikaro** [comment]
Будет Изменено/исправлено в R7
