### ISSUE TITLE
в дввух крафтах юзается одна микросхема при этом в общем гавно коровье

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#174]
### Тип используемого модпака

Default

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

мне надо скрафтит ьэто
![image](https://user-images.githubusercontent.com/112543401/233845815-cc836de8-fa3d-4be5-a7b9-b989c6c82ad9.png)

### Фактическое поведение

а в итоге это
![image](https://user-images.githubusercontent.com/112543401/233845843-23769479-ac84-4194-82e8-2b9d2eba1610.png)

### Действия по воспроизведению

надо просто засунут ьв верстак и будет крафтиться дверь

### Дополнительная информация

поменяй для двери микруху

**Comment by Xikaro** [comment]
Исправил, будет 4 схема, на серве после перезапуска заработает
