### ISSUE TITLE
Ежечасное сверхзависание от семян

### ISSUE THREAD

**Issue by 8oyNextDoor** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#176]
### Тип используемого модпака

Extended

### Среда запуска

Одиночка

### С какой стороны краш

Сервер

### Новые миры

Да

### Действия по воспроизведению

Загрузить чанк с растущими семенами

### Отчет о сбое

https://gist.github.com/8oyNextDoor/ca322c16fe1eda658081a0db282b5023

### Дополнительная информация

Посадил табак и коку, теперь стабильно крашится где-то после часа игры. Происходило при телепортации, пешком не пробовал подходить, состояния мира и инвентаря сохраняются и не сбрасываются

**Comment by Xikaro** [comment]
это дефолт, исправлено в  грядущей версии модпака R7.0.0
