### ISSUE TITLE
Пространственные пилоны крашат сервер при попытке телепортировать провода из гречки

### ISSUE THREAD

**Issue by Strannick112** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#178]
### Version modpack Used

Default

### Environment

Forge Server

### Side Crashed

Server

### New Worlds

Yes

### Steps to Reproduce

1. Поставить любой провод из гречки;
2. Записать его на пространственный диск при помощи пространственных пилонов;
3. Распаковать его обратно в мир с пространственного диска (краш).

### Crash Report

[debug-1.log.gz](https://github.com/TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x/files/11364732/debug-1.log.gz)
[2023-05-01-4.log.gz](https://github.com/TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x/files/11364733/2023-05-01-4.log.gz)
[crash-2023-05-01_12.23.16-server.txt](https://github.com/TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x/files/11364734/crash-2023-05-01_12.23.16-server.txt)

### Additional Information

После краша нужно перепоставить провод, поскольку он перестаёт проводить энергию

**Comment by Xikaro** [comment]
Известная ошибка гт, с нашей стороны не исправить, ждать только разрабов, временное решение, отключать энергопитание или переносить без проводов
