### ISSUE TITLE
Телескоп не может работать из-за недостатка энергии

### ISSUE THREAD

**Issue by Strannick112** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#179]
### Тип используемого модпака

Default

### Среда запуска

Forge Server

### Новые миры

Да

### Ожидаемое поведение

Ожидается, что к телескопу можно подключить провода, либо положить любые батарейки, кроме атомной.

### Фактическое поведение

В телескоп можно положить только атомную батарейку. Её питания не хватает телескопу для работы. Телескоп потребляет энергию постоянно, вне зависимости от того, включен он или нет. Таким образом нельзя даже зарядить телескоп заранее, чтобы потом провести исследование.

### Действия по воспроизведению

Для подключения энергии через провод:
1. Поставить телескоп;
2. Подключить к нему провод снизу;

Для подключения через батарейку:
1. Поставить телескоп;
2. Попытаться запихнуть внутрь батарейку (вставляется только атомная батарейка).

### Дополнительная информация

Из-за этой проблемы невозможно изучить любые планеты, кроме луны, а значит и улететь. Таким образом 90% контента из мода Galacticraft оказывается недоступным.

**Comment by Xikaro** [comment]
атомной хватает, просто кажется что ее мало, но исследование идет

**Comment by Xikaro** [comment]
![Screenshot_56](https://user-images.githubusercontent.com/55663835/235493152-2dbbb81f-385c-421c-9689-81853c0c11d7.png)
![Screenshot_55](https://user-images.githubusercontent.com/55663835/235493156-fdc4dfac-184f-47e3-87ec-9a789c4b38fe.png)


Пофикшено в обнове xD
