### ISSUE TITLE
Крафт еды через Applied Energistics 2

### ISSUE THREAD

**Issue by Strannick112** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#180]
### Тип используемого модпака

Default

### Среда запуска

Forge Server

### Новые миры

Да

### Ожидаемое поведение

Ожидается, что шаблоны рецептов в Applied Energistics 2 не будут обращать внимания на свежесть еды в рецепте.

### Фактическое поведение

Шаблоны рецептов в Applied Energistics 2 принимают еду только определённой свежести

### Действия по воспроизведению

1. Записать шаблон с использованием любой еды с показателем свежести;
2. Заказать в сети Applied Energistics 2 предмет, по созданному шаблону;
3. Если еда использовалась в качестве входного предмета для рецепта - то рецепт не видит еду с другой свежестью, если еда была результатом рецепта - то можно заказать крафт, но сеть может не увидеть, что еда уже готова, поскольку у неё другая свежесть.

**Comment by Xikaro** [comment]
проблема совместимости, будет изменено после выхода R7
