### ISSUE TITLE
Батарейный накопитель и OpenComputers

### ISSUE THREAD

**Issue by Strannick112** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#182]
### Тип используемого модпака

Default

### Среда запуска

Forge Server

### Новые миры

Да

### Ожидаемое поведение

Ожидается, что opencomputers может считать содержимое батарейного накопителя при помощи адаптера хоть в каком-нибудь виде

### Фактическое поведение

Адаптер из opencomputers просто не видит батарейного накопителя вообще.

### Действия по воспроизведению

1. Поставить батарейный накопитель в мир;
2. Наполнить его батарейками;
3. Поставить вплотную к накопителю адаптер;
4. Подключить адаптер к компьютеру из opencomputers;
5. Включить компьютер с операционной системой OpenOS;
7. Выполнить команду lua;
8. Выполнить команду "for k, v in component.list() do print(k, v) end".

### Дополнительная информация

![image](https://user-images.githubusercontent.com/43038491/235437921-70995838-c9e2-45d7-aa97-5ce89ea3414c.png)

**Comment by Xikaro** [comment]
У гт и oc нет встроенной поддержки друг друга, с нашей стороны это так же не исправимо, только ждать что когда нибудь доделают аддон для GTCEu

https://github.com/GregTechCEu/Gregification
