### ISSUE TITLE
Отсутствует описание квеста на англ. версии

### ISSUE THREAD

**Issue by 8oyNextDoor** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#185]
### Тип используемого модпака

Extended

### Среда запуска

Одиночка

### Новые миры

Да

### Ожидаемое поведение

Наличие описания квеста

### Фактическое поведение

Есть только отсылка на описание

### Действия по воспроизведению

Вот этот квест в ХВ ветке
![image](https://user-images.githubusercontent.com/130379681/235453027-59b4c9b9-61ea-43ce-8ffc-15e703e15632.png)

**Comment by Xikaro** [comment]
исправил
