### ISSUE TITLE
Will there be server packs for 4.3.0 Extended?

### ISSUE THREAD

**Issue by Vetpetmon** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#199]
### Your Question

Hello! I have a Linux server that needs to be running the latest version of the modpack in hopes of fixing the Galacticraft issue with the planet dimensions not loading in, but there is no server pack for the latest version! In the meantime, is there anything I can do to fix the issue in particular?

**Comment by Xikaro** [comment]
https://github.com/TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x/releases/tag/R4.3.0

Hello, there is a version available on the git
