### ISSUE TITLE
В горшок нельзя положить очевидно маленькие вещи.

### ISSUE THREAD

**Issue by BayerHeroine** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#21]
### Modpack Used

TFG 4.1.4

### Environment

Singleplayer

### New Worlds

No

### Cross-Mod Interaction

No

### Expected Behavior

Некоторые вещи почему-то нельзя положить в горшок. Семена меньше камней, но (в цирке не выступают) в горшок их нельзя положить.  Или пепел например. Это же пыль по сути. Зато глину можно положить, которая очевидно больше.

### Actual Behavior

Полагаю что это баг, потому что раньше подобные вещи можно было класть в горшок. Мне кажется, дело в том, что горшок может хранить либо только маленькие вещи (что не означает, что туда влезут очень маленькие) или любую пищу (независимо от размеров).

### Steps to Reproduce

1) берем очень маленькую вещь (не пищу), например нитки
2) наслаждаемся как она не влазит в горшок

**Comment by BayerHeroine** [comment]
Ну тот, что 2х2 клетки. Vessel

**Comment by ExpectoAmogus** [comment]
В сосуд, теперь можно складывать только еду, и предметы, которые там можно расплавить

**Comment by Xikaro** [comment]
Верно, это сделано намеренно

**Comment by Xikaro** [comment]
Для хранения других вещей используй ящик тфкфлорае

**Comment by Xikaro** [comment]
Костыль из-за чего это было сделано изначально, будет исправлен в форке
https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=25746199

Перенес в todo
