### ISSUE TITLE
Chunkloading Invalidates TFC Chunk Data

### ISSUE THREAD

**Issue by AtelierAmber** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#32]
### Modpack Used

TFG:NH Extended R4.1.6a

### Environment

Singleplayer

### New Worlds

Yes

### Cross-Mod Interaction

Unsure

### Expected Behavior

The TerraFirmaCraft chunk data should be shown.

![image](https://user-images.githubusercontent.com/22966571/199062364-460ef16f-b8aa-4e11-8d11-a682e2207ceb.png)

### Actual Behavior

But when you chunk load a chunk with the chunk claiming mod it will invalidate the chunk data. I'm not sure if this has any real problems but it's worth noting. I didn't see any errors in the logs but I've included them anyways

![image](https://user-images.githubusercontent.com/22966571/199063334-b673b539-c550-4793-bbd5-003701237335.png)

[latest.log](https://github.com/TerraFirmaGreg-New-Horizons/TFG-NewHorizons-1.12.2/files/9903175/latest.log)

### Steps to Reproduce

1) Press f3 to check that the chunk data is not invalidated
2) Chunkload a chunk
3) Save and quite
4) Load the world again
5) Press f3 to see the Invalid Chunk Data

**Comment by SpeeeDCraft** [comment]
Thanks

**Comment by Xikaro** [comment]
The FTB compatibility problem will most likely be fixed with the release of the fork of tfс and ftb, for now I see no reason to keep it open

https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=25746252
