### ISSUE TITLE
Создание нового механизма

### ISSUE THREAD

**Issue by Maximnety** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#33]
### Modpack Used

TFG

### Related Problem

Паровой век, а свариваем слитки до сих пор вручную

### Your Solution

Решение - создание нового парового механизма, сварщика. Он будет сваривать слитки в сдвоенные, которые можно будет перековать в кузнечном молоте в двойные пластины.

**Comment by Xikaro** [comment]
https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=25746266
Будет решаться в рамках форка тфк, перенес задачу, тут закрою
