### ISSUE TITLE
Агрокультуры (ошибки, нет дропа)

### ISSUE THREAD

**Issue by Neon4301** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#34]
### Modpack Used

R4.16.a

### Environment

сервер

### New Worlds

Yes

### Cross-Mod Interaction

Unsure

### Expected Behavior

соберу урожай 

### Actual Behavior

краш или нет дропа

### Steps to Reproduce

вырастить одну из культур:
___---не имеют дропа---___
1 спаржевая фасоль - black eyed pears
2 сахарная свекла - sugar beet
3 женьшень - ginseng
4 кайнейского? перец - Cayenne pepper
5 брюква - Rutabaga
6 репа - turnip
7 полба - spelt
___---крашит---____
1 крашит tile.firmalife.corp.melon.name -  когда культура мертва она не крашит
2 pumpkin

**Comment by Xikaro** [comment]
краши исправлены

**Comment by Xikaro** [comment]
https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=25746286
перенес
