### ISSUE TITLE
Небольшая подсказка

### ISSUE THREAD

**Issue by JedaiGames** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#49]
### Тип используемого модпака

Default

### Связанная проблема

В TerraFirmaCraft есть стартовая кровать изготавливаемая из блоков сена и большой шкуры.
Она не позволяет пропускать ночь, но позволяет ставить точку возрождения.
Думаю некоторым игрокам, которые не сильно разбираются в TFC было бы полезно узнать об этом.

### Ваше решение

Добавить квест-обучалку на тему как сделать первобытную кровать
(Поставить рядом два блока сена и кликнуть по ним большой шкурой пкм)

**Comment by nemo48rus** [comment]
Поддерживаю. Не очевидная механика была.

**Comment by FriendlyCube** [comment]
настоящие гигачады спят на земле
![image](https://user-images.githubusercontent.com/112543401/232606848-459e20fd-53f2-41d4-89dc-fc39e67eec4e.png)

**Comment by Xikaro** [comment]
сделал
