### ISSUE TITLE
Добавить части для крафта ТФКолы в данжах GC

### ISSUE THREAD

**Issue by nemo48rus** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#5]
Будет какой-то азарт при поиске компонентов (отдельных) и сбора их вместе.
Если даёт бонус к передвижению продолжительный как палка, то вообще найс.

**Comment by Xikaro** [comment]
В форке тфк, это скорее всего удалится, так что пока на закрытие
