### ISSUE TITLE
Reliable Source of Vanilla water / Allow Freshwater to be used in Gregtech Machine Recipes

### ISSUE THREAD

**Issue by BigMaxPorter** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#50]
### Version modpack Used

Default

### Related Problem

Many gregtech recipes (such as making paper out of wood pulp and water in the chemical bath) require vanilla minecraft water. As it stands, I can find no way to reliably get vanilla water in any substantial quantity.

### Your Solution

Either make freshwater work in place of vanilla water in all the gregtech recipes that require it (A tall order, I know) or add a way to get vanilla water easily. Maybe have the primitive water pump put out vanilla water instead of TFC freshwater as there is a way to convert TFC water into vanilla, but not the other way around.

**Comment by BigMaxPorter** [comment]
Right now the only way I can see to easily get sufficient amounts of vanilla water is using the infinite water cover, which is locked to HV

**Comment by BigMaxPorter** [comment]
Apparently this was already in the works :)

**Comment by Xikaro** [comment]
While let it be open, I will close it when the release is released

**Comment by msgerbs** [comment]
Was this ever added?

**Comment by Xikaro** [comment]
this will be implemented in a fork of tfc, or in an addon to gt

**Comment by msgerbs** [comment]
Can we at least get a conversion recipe in the meantime? This is pretty important to GT progression, and I honestly don't understand how other people are dealing with this.

**Comment by Xikaro** [comment]
there are recipes for obtaining distilled water, it is suitable for recipes, and there is also an improvement of infinite water, for stages from HV

**Comment by Xikaro** [comment]
https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=25746309
Перенес задачу

**Comment by msgerbs** [comment]
Thank you! I do want to point out though, that all of the recipes for distilled water require vanilla water and don't work with fresh water either, so this is very much needed. I appreciate you working on it.

**Comment by FirinMaLazors** [comment]
You can get infinite vanilla water by manually placing some over a water biome, e.g. lake or ocean, in a pool; they will reproduce as usual, and you can use a LV pump to get it out.
