### ISSUE TITLE
Новые возможности изменения температуры в помещениях

### ISSUE THREAD

**Issue by DariyFirst** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#52]
### Тип используемого модпака

Default

### Связанная проблема

Можно реализовать систему при которой трубы с горячими газами или жидкостями будут работать как обогреватель, а трубы с холодными газами или жидкостями наоборот остужают окружающее пространство.

### Ваше решение

Добавить квест который расскажет про такую систему.

**Comment by Xikaro** [comment]
https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=25746355
перенес задачу
