### ISSUE TITLE
Идея: Streams

### ISSUE THREAD

**Issue by KarandashKosmos** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#61]
### Тип используемого модпака

Default

### Связанная проблема

К сожалению в оригинальном TFC генерация рек не самая хорошая (да и их не всегда найдёшь).

### Ваше решение

Я предлагаю добавить мод Streams, который изменяет генерацию рек. Он совместим с TFC и есть на 1.12.2.

### Дополнительная информация

Мод: https://www.curseforge.com/minecraft/mc-mods/streams.

**Comment by SpeeeDCraft** [comment]
Мод не работает с TFC на 1.12. Но так как мы сейчас переписываем TFC, мы его обязательно постараемся добавить. Я на самом деле тоже хочу чтобы он был в модпаке.

**Comment by KarandashKosmos** [comment]
Спасибо! Я думаю он украсит мир.

**Comment by Xikaro** [comment]
https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=25746379
перенес задачу
