### ISSUE TITLE
Камнелом в паровой эпохе

### ISSUE THREAD

**Issue by caxapexac** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#70]
### Your Question

Камнелом требует блок ванильной майнкрафтовой воды, но её нельзя легально добыть в паровой эпохе. Камнелом не работает с salt water/fresh water из террафирмы

Workaround: рыбалкой выловить бутылку для зелий и наполнить котёл, бутылка конвертирует воду в ванильную. По идее это баг, но в итоге он является единственным способом юзать камнелом

Ещё на камнелом нету квеста

**Comment by Xikaro** [comment]
это будет исправлено как мы закончим с переписыванием тфк 
https://github.com/TerraFirmaGreg-New-Horizons/TFG-TerraFirmaCraft-1.12.2
Так как пока в гт нет метода CT, который позволит менять жидкость, с которой взаимодействует камнелом

Пока оставлю открытым

**Comment by Damodigy** [comment]
Можно, надо лишь немного заморочиться. Ванильный котёл и бутылка ванильная тебе в помощь.

**Comment by caxapexac** [comment]
> Можно, надо лишь немного заморочиться. Ванильный котёл и бутылка ванильная тебе в помощь.

Но я же это и написал выше...

**Comment by Damodigy** [comment]
Я видимо немного слеповат извиняюсь

**Comment by Xikaro** [comment]
Старость

**Comment by Xikaro** [comment]
в паровой эре щас не предусмотрены рецепты, так что пока я это закрою
