### ISSUE TITLE
Переработка TFC вещей

### ISSUE THREAD

**Issue by GIBRID64r** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#88]
### Ваш вопрос

Предлагаю сделать так что бы вещи и предметы из TFC можно было сделать в GT машинках (Сплавы, гарпуны, и т.д). А так же их разбор(Как в дробителе, дуговой печи).Просто они стоят если уже пройден Примитив.

**Comment by Xikaro** [comment]
https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=25746384
перенес
