### ISSUE TITLE
Малый сосуд, вместимость жидкого металла

### ISSUE THREAD

**Issue by TheDeaX-Lab** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#90]
### Тип используемого модпака

Default

### Связанная проблема

В настоящий момент наблюдается ситуация, что в горшке может вмещаться только 4000 mb жидкого металла, как это было в обычном тфк, но из-за того, что на 1 слиток тратится 144 mb, мы получаем не 40 слитков, а 27 слитков и  112 mb в остатке.

### Ваше решение

Ожидается, что мы будем также сохранять вместимость малого сосуда до 40 слитков с учетом нововведений затрат на 1 слиток, т.е. суммарная вместимость 5760 mb. Если этого сделать быстро не получится или не согласны с тем что он должен хранить именно такое количество, то добавить к сосуду подпись, что он хранит не более чем 4000 mb.

**Comment by SpeeeDCraft** [comment]
Знаем о проблеме, исправим как только представится возможность, сейчас загруженность высокая :)

**Comment by Xikaro** [comment]
https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=25746403
