### ISSUE TITLE
Учет опыт ковки TFC на инструменты GregTech

### ISSUE THREAD

**Issue by TheDeaX-Lab** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#92]
### Тип используемого модпака

Default

### Связанная проблема

Раньше опыт ковки приносил прочность и скорость копки инструмента. Сейчас проблема, что к наголовью инструмента приходит опыт ковки, но при соединении с палкой он теряет опыт ковки.

### Ваше решение

Хотелось бы чтобы надпись копировалась на создаваемый инструмент и увеличивала его прочность на такой же процент как и опыт ковки, максимальный 100%.

**Comment by SpeeeDCraft** [comment]
Очень сложно реализуемо, учитывая специфику ГТ инструментов, оставлю открытым, но врятли будет реализовано

**Comment by Xikaro** [comment]
https://github.com/orgs/TerraFirmaGreg-New-Horizons/projects/3/views/1?pane=issue&itemId=24881869
