### ISSUE TITLE
Проблема промывки руды на котле

### ISSUE THREAD

**Issue by TheDeaX-Lab** [TerraFirmaGreg-New-Horizons/TFG-Modpack-1.12.x#93]
### Тип используемого модпака

Default

### Связанная проблема

Наблюдается проблема что руда после дробления не промывается в котле с пресной и холодной водой. Также наблюдается что с грязной пылью любой руды превращается в 2 мелких промытых кусочка, хотя по скриншоту схему промывания в котле совсем другие и они не исполняются из-за приоритета другого мода
![image](https://user-images.githubusercontent.com/28222565/215117492-c9315172-a8bb-45e0-85fe-3ec13ce6947d.png)
![image](https://user-images.githubusercontent.com/28222565/215117539-f126a326-970e-4831-b5ab-0c1f02fd6abd.png)

### Ваше решение

Надо переопределить приоритеты, если что-то происходит конкретно в котле - тот мод свыше действовать на него не должен, а действует gregtech как было по канону, если промывают игроки без котла - тогда да в этом есть смысл, что часть руды улетает в море, но в жизни если промывать в герметичном котле, остатки также останутся в котле и не растеряется. В любом случае должна быть какая-то промежуточная мотивация в развитии до железа, где от промывки на котле будет профит, на LV уровне и паровом естественно будет тоже лучше

**Comment by Xikaro** [comment]
Исправлено в грядущем тотальном обновлении модпака R7.0.0
А пока придется потерпеть
